apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
spec:
  project: default
  source:
    repoURL:https://github.com/Feugana1/guestbook-gitops.git
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true      # Supprime les objets orphelins
      selfHeal: true   # Auto-healing
    syncOptions:
    - CreateNamespace=true

